//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.EmailTemplates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AccurateAppend {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccurateAppend() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DomainModel.EmailTemplates.AccurateAppend", typeof(AccurateAppend).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///
        ///&lt;!-- footer --&gt;
        ///&lt;tr&gt;
        /// &lt;td bgcolor=&quot;#fafafa&quot;&gt;
        ///  &lt;table class=&quot;w-100p&quot; width=&quot;600&quot; align=&quot;center&quot; style=&quot;max-width:600px; margin:0 auto;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///   &lt;tr&gt;
        ///    &lt;td style=&quot;padding:32px 18px;&quot;&gt;
        ///     &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///      &lt;tr&gt;
        ///       &lt;td style=&quot;padding:0 0 33px; border-bottom:2px solid #eee;&quot;&gt;
        ///        &lt;table align=&quot;center&quot; style=&quot;margin:0 auto;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///         &lt;tr&gt;
        ///          &lt;td class=&quot;active-i&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodyFooter {
            get {
                return ResourceManager.GetString("BodyFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body bgcolor=&quot;#ffffff&quot; style=&quot;margin:0; padding:0; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%;&quot;&gt;
        ///
        /// &lt;table class=&quot;gmail-fix&quot; bgcolor=&quot;#ffffff&quot; width=&quot;100%&quot; style=&quot;min-width:320px;&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///  &lt;!-- header --&gt;
        ///  &lt;tr&gt;
        ///   &lt;td bgcolor=&quot;#5cb4e3&quot;&gt;
        ///    &lt;table class=&quot;w-100p&quot; width=&quot;600&quot; align=&quot;center&quot; style=&quot;max-width:600px; margin:0 auto;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///     &lt;tr&gt;
        ///      &lt;td class=&quot;plr-10&quot; style=&quot;padding:12px 18px 23px;&quot;&gt;
        ///       &lt;a style=&quot;text-decorati [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodyHeader {
            get {
                return ResourceManager.GetString("BodyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- START customer care block --&gt;
        ///  &lt;tr&gt;
        ///   &lt;td bgcolor=&quot;#437fa2&quot; style=&quot;padding: 4px;&quot;&gt;
        ///    &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///     &lt;tr&gt;
        ///      &lt;td class=&quot;plr-10 fs-16 lh-20&quot; bgcolor=&quot;#5cb4e3&quot; align=&quot;center&quot; style=&quot;padding: 16px 30px 20px; font: 20px/23px Arial, Helvetica, sans-serif; color: #fff;&quot;&gt;
        ///       Call customer care &lt;b&gt;&lt;a style=&quot;color: #fff; text-decoration: underline;&quot; href=&quot;tel:{0}&quot;&gt;{0}&lt;/a&gt;&lt;/b&gt; or&amp;nbsp;email &lt;b&gt;&lt;a style=&quot;color: #fff; text-decoration: underline;&quot; href=&quot;mai [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContentCustomerCareBlock {
            get {
                return ResourceManager.GetString("ContentCustomerCareBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;/table&gt;
        ///  &lt;!-- END content area --&gt;.
        /// </summary>
        public static string ContentEnd {
            get {
                return ResourceManager.GetString("ContentEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;!-- START content area --&gt;
        ///  &lt;table class=&quot;w - 100p&quot; width=&quot;600&quot; align=&quot;center&quot; style=&quot;max - width: 600px; margin: 0 auto;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;.
        /// </summary>
        public static string ContentStart {
            get {
                return ResourceManager.GetString("ContentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- START terms block --&gt;
        ///    &lt;tr&gt;
        ///        &lt;td style=&quot;padding: 25px 0 20px; border-top: 2px solid #eaeaea;&quot;&gt;
        ///            &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td style=&quot;padding: 0 0 9px; font: bold 12px/16px Arial, Helvetica, sans-serif; color: #000; text-transform: uppercase;&quot;&gt;
        ///                        1. CONFIDENTIALITY
        ///                    &lt;/td&gt;
        ///                &lt;/tr&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td style=&quot;padding: 0 0 9px; fon [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContentTac {
            get {
                return ResourceManager.GetString("ContentTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        /// &lt;title&gt;AccurateAppend_email&lt;/title&gt;
        /// &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        /// &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        /// &lt;style type=&quot;text/css&quot;&gt;
        ///  a {
        ///   outline: none;
        ///   color: #000;
        ///   text-decoration: underline;
        ///  }
        ///
        ///   a:hover {
        ///    text-decoration: none !important;
        ///   }
        ///
        ///  .h-u a {
        ///   text-decoration: none;
        ///  }
        ///
        ///   .h-u a:hover {
        ///    text-decoration: underline !important;
        ///   }
        ///
        ///  a[x-apple-data-detectors] {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;.
        /// </summary>
        public static string HtmlDeclaration {
            get {
                return ResourceManager.GetString("HtmlDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/html&gt;.
        /// </summary>
        public static string HtmlEnd {
            get {
                return ResourceManager.GetString("HtmlEnd", resourceCulture);
            }
        }
    }
}
