<%@ Page Title="" Language="C#" MasterPageFile="~/Views/Shared/bootstrap3.Master" Inherits="System.Web.Mvc.ViewPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
    CIM Form
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
 
 <ul id="notification"></ul>
 <br/>
 <iframe src="<%: this.Url.Action("DisplayForm", "EditCreditCard", new { paymentId=1921369413}) %>" width="1200" height="600" style="margin: 0; padding: 0; border: none;"></iframe>

 <script>
 $(function() {
  // Reference the auto-generated proxy for the hub.  
  var channel = $.connection.callbackHub;
  
  // Create a function that the hub can call back to display messages.
  channel.client.addNewMessageToPage = function (message) {
   alert(message);
  };
  // Start the connection.
  $.connection.hub.start().done(function() {  });
 });
 </script>
  </asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="DocumentStart" runat="server">
 <script src="/Scripts/jquery.signalR-2.4.1.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>

 
</asp:Content>