//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccurateAppend.Websites.Admin.Areas.Accounting.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaymentUpdateTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentUpdateTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccurateAppend.Websites.Admin.Areas.Accounting.Data.PaymentUpdateTemplate", typeof(PaymentUpdateTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;!-- START intro block --&gt;
        ///  &lt;tr&gt;
        ///   &lt;td class=&quot;pt-35 plr-0&quot; style=&quot;padding: 54px 20px 36px;&quot;&gt;
        ///    &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///     &lt;tr&gt;
        ///      &lt;td class=&quot;fs-18&quot; style=&quot;padding: 0 0 24px; font: bold 22px/26px Arial, Helvetica, sans-serif; color: #000;&quot;&gt;
        ///       Update Payment
        ///      &lt;/td&gt;
        ///     &lt;/tr&gt;
        ///     &lt;tr&gt;
        ///      &lt;td class=&quot;fs-12 lh-20&quot; style=&quot;padding: 0 0 28px; font: 16px/24px Arial, Helvetica, sans-serif; color: #000; border-bottom: 2px solid #eaeaea;&quot;&gt;
        ///       &lt;p&gt;We at [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentIntroBlockDeal {
            get {
                return ResourceManager.GetString("ContentIntroBlockDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;!-- START intro block --&gt;
        ///  &lt;tr&gt;
        ///   &lt;td class=&quot;pt-35 plr-0&quot; style=&quot;padding: 54px 20px 36px;&quot;&gt;
        ///    &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///     &lt;tr&gt;
        ///      &lt;td class=&quot;fs-18&quot; style=&quot;padding: 0 0 24px; font: bold 22px/26px Arial, Helvetica, sans-serif; color: #000;&quot;&gt;
        ///       Update Payment
        ///      &lt;/td&gt;
        ///     &lt;/tr&gt;
        ///     &lt;tr&gt;
        ///      &lt;td class=&quot;fs-12 lh-20&quot; style=&quot;padding: 0 0 28px; font: 16px/24px Arial, Helvetica, sans-serif; color: #000; border-bottom: 2px solid #eaeaea;&quot;&gt;
        ///       &lt;p&gt;Your  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentIntroBlockUser {
            get {
                return ResourceManager.GetString("ContentIntroBlockUser", resourceCulture);
            }
        }
    }
}
