//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccurateAppend.Websites.Admin.Areas.Accounting.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReceiptTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReceiptTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccurateAppend.Websites.Admin.Areas.Accounting.Data.ReceiptTemplate", typeof(ReceiptTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;!-- END Common Attachments block --&gt;.
        /// </summary>
        internal static string ContentAttachmentsBlockEnd {
            get {
                return ResourceManager.GetString("ContentAttachmentsBlockEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;!-- START Common Attachments block --&gt;
        ///  &lt;tr&gt;
        ///   &lt;td class=&quot;fs-18&quot; style=&quot;padding: 31px 0 25px; font: bold 22px/26px Arial, Helvetica, sans-serif; color: #5cb4e3;&quot;&gt;
        ///    Download Files
        ///   &lt;/td&gt;
        ///  &lt;/tr&gt;.
        /// </summary>
        internal static string ContentAttachmentsBlockStart {
            get {
                return ResourceManager.GetString("ContentAttachmentsBlockStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;!-- START file details block --&gt;
        ///  &lt;tr&gt;
        ///   &lt;td class=&quot;fs-18&quot; style=&quot;padding: 0 0 25px; font: bold 22px/26px Arial, Helvetica, sans-serif; color: #5cb4e3;&quot;&gt;
        ///    Order Details
        ///   &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///   &lt;td style=&quot;border: 1px solid #ddd;&quot;&gt;
        ///    &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///     &lt;tr&gt;
        ///      &lt;td class=&quot;w-100&quot; width=&quot;145&quot; valign=&quot;top&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5 fs-12 lh-20&quot; style=&quot;padding: 10px; font: b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentFileDetailsBlock {
            get {
                return ResourceManager.GetString("ContentFileDetailsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;!-- START intro block --&gt;
        ///  &lt;tr&gt;
        ///   &lt;td class=&quot;pt-35 plr-0&quot; style=&quot;padding: 54px 20px 36px;&quot;&gt;
        ///    &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///     &lt;tr&gt;
        ///      &lt;td class=&quot;fs-18&quot; style=&quot;padding: 0 0 24px; font: bold 22px/26px Arial, Helvetica, sans-serif; color: #000;&quot;&gt;
        ///       Processing Complete
        ///      &lt;/td&gt;
        ///     &lt;/tr&gt;
        ///     &lt;tr&gt;
        ///      &lt;td class=&quot;fs-12 lh-20&quot; style=&quot;padding: 0 0 28px; font: 16px/24px Arial, Helvetica, sans-serif; color: #000; border-bottom: 2px solid #eaeaea;&quot;&gt;
        ///       You [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentIntroBlock {
            get {
                return ResourceManager.GetString("ContentIntroBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- START intro block --&gt;
        ///  &lt;tr&gt;
        ///   &lt;td class=&quot;pt-35 plr-0&quot; style=&quot;padding: 54px 20px 36px;&quot;&gt;
        ///    &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///     &lt;tr&gt;
        ///      &lt;td class=&quot;fs-18&quot; style=&quot;padding: 0 0 24px; font: bold 22px/26px Arial, Helvetica, sans-serif; color: #000;&quot;&gt;
        ///       Processing Complete
        ///      &lt;/td&gt;
        ///     &lt;/tr&gt;
        ///     &lt;tr&gt;
        ///      &lt;td class=&quot;fs-12 lh-20&quot; style=&quot;padding: 0 0 28px; font: 16px/24px Arial, Helvetica, sans-serif; color: #000; border-bottom: 2px solid #eaeaea;&quot;&gt;
        ///       Your  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentIntroBlockWithDownload {
            get {
                return ResourceManager.GetString("ContentIntroBlockWithDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      &lt;tr&gt;
        ///      &lt;td valign=&quot;top&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5 fs-12 lh-20&quot; style=&quot;padding: 10px; font: 16px/24px Arial, Helvetica, sans-serif; color: #000;&quot;&gt;
        ///          {0}
        ///         &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///       &lt;/table&gt;
        ///      &lt;/td&gt;
        ///      &lt;td width=&quot;1&quot; bgcolor=&quot;#dddddd&quot;&gt;&lt;/td&gt;
        ///      &lt;td class=&quot;w-70&quot; width=&quot;130&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5 fs-12 lh-20&quot; align= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentLineItem {
            get {
                return ResourceManager.GetString("ContentLineItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/table&gt;
        ///   &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;!-- END line items block --&gt;.
        /// </summary>
        internal static string ContentLineItemsBlockEnd {
            get {
                return ResourceManager.GetString("ContentLineItemsBlockEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;!-- START line items block --&gt;
        ///  &lt;tr&gt;
        ///   &lt;td class=&quot;fs-18&quot; style=&quot;padding: 31px 0 25px; font: bold 22px/26px Arial, Helvetica, sans-serif; color: #5cb4e3;&quot;&gt;
        ///    Items
        ///   &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///   &lt;td style=&quot;border: 1px solid #ddd;&quot;&gt;
        ///    &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///     &lt;tr&gt;
        ///      &lt;td valign=&quot;top&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5 fs-12 lh-20&quot; style=&quot;padding: 10px; font: bold 16px/24px Arial, Helvetica, s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentLineItemsBlockStart {
            get {
                return ResourceManager.GetString("ContentLineItemsBlockStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/table&gt;
        ///   &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;!-- END match detail block --&gt;.
        /// </summary>
        internal static string ContentProcessingDetailBlockEnd {
            get {
                return ResourceManager.GetString("ContentProcessingDetailBlockEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;!-- START match detail block --&gt;
        ///  &lt;tr&gt;
        ///   &lt;td class=&quot;fs-18&quot; style=&quot;padding: 31px 0 25px; font: bold 22px/26px Arial, Helvetica, sans-serif; color: #5cb4e3;&quot;&gt;
        ///    Details
        ///   &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///   &lt;td style=&quot;border: 1px solid #ddd;&quot;&gt;
        ///    &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///     &lt;tr&gt;
        ///      &lt;td valign=&quot;top&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5 fs-12 lh-20&quot; style=&quot;padding: 10px; font: bold 16px/24px Arial, Helvetic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentProcessingDetailBlockStart {
            get {
                return ResourceManager.GetString("ContentProcessingDetailBlockStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      &lt;tr&gt;
        ///      &lt;td valign=&quot;top&quot; colspan=&quot;3&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5 fs-12 lh-20&quot; style=&quot;padding: 10px; ont: 16px/24px Arial, Helvetica, sans-serif; color: #000;&quot;&gt;
        ///          {0}
        ///         &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///       &lt;/table&gt;
        ///      &lt;/td&gt;
        ///      &lt;td width=&quot;1&quot; bgcolor=&quot;#dddddd&quot;&gt;&lt;/td&gt;
        ///      &lt;td class=&quot;w-70&quot; width=&quot;122&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5 fs-12 lh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentProcessingDetailItemDeliverability {
            get {
                return ResourceManager.GetString("ContentProcessingDetailItemDeliverability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      &lt;tr&gt;
        ///      &lt;td valign=&quot;top&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5 fs-12 lh-20&quot; style=&quot;padding: 10px; font: 16px/24px Arial, Helvetica, sans-serif; color: #000;&quot;&gt;
        ///          {0}
        ///         &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///       &lt;/table&gt;
        ///      &lt;/td&gt;
        ///      &lt;td width=&quot;1&quot; bgcolor=&quot;#dddddd&quot;&gt;&lt;/td&gt;
        ///      &lt;td class=&quot;w-70&quot; width=&quot;130&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5 fs-12 lh-20&quot; align= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentProcessingDetailItemFirst {
            get {
                return ResourceManager.GetString("ContentProcessingDetailItemFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      &lt;tr&gt;
        ///      &lt;td valign=&quot;top&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5 fs-12 lh-20&quot; style=&quot;padding: 10px; font: 16px/24px Arial, Helvetica, sans-serif; color: #000;&quot;&gt;&lt;/td&gt;
        ///        &lt;/tr&gt;
        ///       &lt;/table&gt;
        ///      &lt;/td&gt;
        ///      &lt;td width=&quot;1&quot; bgcolor=&quot;#dddddd&quot;&gt;&lt;/td&gt;
        ///      &lt;td class=&quot;w-70&quot; width=&quot;130&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5 fs-12 lh-20&quot; align=&quot;right&quot; style=&quot;padding: 10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentProcessingDetailItemSubsequent {
            get {
                return ResourceManager.GetString("ContentProcessingDetailItemSubsequent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      &lt;tr&gt;
        ///      &lt;td valign=&quot;top&quot; colspan=&quot;3&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5 fs-12 lh-20&quot; style=&quot;padding: 10px; font: bold 16px/24px Arial, Helvetica, sans-serif; color: #000;&quot;&gt;
        ///          Total
        ///         &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///       &lt;/table&gt;
        ///      &lt;/td&gt;
        ///      &lt;td width=&quot;1&quot; bgcolor=&quot;#dddddd&quot;&gt;&lt;/td&gt;
        ///      &lt;td class=&quot;w-70&quot; width=&quot;122&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentProcessingDetailItemTotals {
            get {
                return ResourceManager.GetString("ContentProcessingDetailItemTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/table&gt;
        ///   &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;!-- END match summary block --&gt;.
        /// </summary>
        internal static string ContentProcessingSummaryBlockEnd {
            get {
                return ResourceManager.GetString("ContentProcessingSummaryBlockEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      &lt;tr&gt;
        ///      &lt;td valign=&quot;top&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5 fs-12 lh-20&quot; style=&quot;padding: 10px; font: 16px/24px Arial, Helvetica, sans-serif; color: #000;&quot;&gt;
        ///          {0}
        ///         &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///       &lt;/table&gt;
        ///      &lt;/td&gt;
        ///      &lt;td width=&quot;1&quot; bgcolor=&quot;#dddddd&quot;&gt;&lt;/td&gt;
        ///      &lt;td class=&quot;w-100&quot; width=&quot;109&quot; valign=&quot;top&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5 fs-12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentProcessingSummaryBlockItem {
            get {
                return ResourceManager.GetString("ContentProcessingSummaryBlockItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;!-- START match summary block --&gt;
        ///  &lt;tr&gt;
        ///   &lt;td class=&quot;fs-18&quot; style=&quot;padding: 31px 0 25px; font: bold 22px/26px Arial, Helvetica, sans-serif; color: #5cb4e3;&quot;&gt;
        ///    Summary
        ///   &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///   &lt;td style=&quot;border: 1px solid #ddd;&quot;&gt;
        ///    &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///     &lt;tr&gt;
        ///      &lt;td valign=&quot;top&quot;&gt;
        ///       &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///         &lt;td class=&quot;plr-5 fs-12 lh-20&quot; style=&quot;padding: 10px; font: bold 16px/24px Arial, Helveti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentProcessingSummaryBlockStart {
            get {
                return ResourceManager.GetString("ContentProcessingSummaryBlockStart", resourceCulture);
            }
        }
    }
}
